
Traceback (most recent call last):
  File "fork-of-regression-challenge-day-3.py", line 12, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation'), ('line_no', 12)])
Traceback (most recent call last):
  File "fork-of-regression-challenge-day-3.py", line 13, in <module>
    from sklearn.utils.validation import train_test_split
ImportError: cannot import name 'train_test_split'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cross_decomposition'), ('line_no', 12)])
Traceback (most recent call last):
  File "fork-of-regression-challenge-day-3.py", line 13, in <module>
    from sklearn.cross_decomposition import train_test_split
ImportError: cannot import name 'train_test_split'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.check_memory'), ('line_no', 12)])
Traceback (most recent call last):
  File "fork-of-regression-challenge-day-3.py", line 13, in <module>
    from sklearn.utils.validation.check_memory import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.check_memory'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.column_or_1d'), ('line_no', 12)])
Traceback (most recent call last):
  File "fork-of-regression-challenge-day-3.py", line 13, in <module>
    from sklearn.utils.validation.column_or_1d import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.column_or_1d'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.check_is_fitted'), ('line_no', 12)])
Traceback (most recent call last):
  File "fork-of-regression-challenge-day-3.py", line 13, in <module>
    from sklearn.utils.validation.check_is_fitted import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.check_is_fitted'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.check_symmetric'), ('line_no', 12)])
Traceback (most recent call last):
  File "fork-of-regression-challenge-day-3.py", line 13, in <module>
    from sklearn.utils.validation.check_symmetric import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.check_symmetric'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cluster.Birch'), ('line_no', 12)])
Traceback (most recent call last):
  File "fork-of-regression-challenge-day-3.py", line 13, in <module>
    from sklearn.cluster.Birch import train_test_split
ModuleNotFoundError: No module named 'sklearn.cluster.Birch'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cluster.KMeans'), ('line_no', 12)])
Traceback (most recent call last):
  File "fork-of-regression-challenge-day-3.py", line 13, in <module>
    from sklearn.cluster.KMeans import train_test_split
ModuleNotFoundError: No module named 'sklearn.cluster.KMeans'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.has_fit_parameter'), ('line_no', 12)])
Traceback (most recent call last):
  File "fork-of-regression-challenge-day-3.py", line 13, in <module>
    from sklearn.utils.validation.has_fit_parameter import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.has_fit_parameter'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cross_decomposition.CCA'), ('line_no', 12)])
Traceback (most recent call last):
  File "fork-of-regression-challenge-day-3.py", line 13, in <module>
    from sklearn.cross_decomposition.CCA import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_decomposition.CCA'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.all_estimators'), ('line_no', 12)])
Traceback (most recent call last):
  File "fork-of-regression-challenge-day-3.py", line 13, in <module>
    from sklearn.utils.all_estimators import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.all_estimators'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.model_selection'), ('line_no', 12)])



[REPAIR EXEC TIME]: 24.728514432907104