
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 181, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 182, in <module>
    from sklearn.utils.validation import train_test_split
ImportError: cannot import name 'train_test_split'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cross_decomposition'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 182, in <module>
    from sklearn.cross_decomposition import train_test_split
ImportError: cannot import name 'train_test_split'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.check_memory'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 182, in <module>
    from sklearn.utils.validation.check_memory import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.check_memory'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.column_or_1d'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 182, in <module>
    from sklearn.utils.validation.column_or_1d import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.column_or_1d'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.check_is_fitted'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 182, in <module>
    from sklearn.utils.validation.check_is_fitted import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.check_is_fitted'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.check_symmetric'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 182, in <module>
    from sklearn.utils.validation.check_symmetric import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.check_symmetric'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cluster.Birch'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 182, in <module>
    from sklearn.cluster.Birch import train_test_split
ModuleNotFoundError: No module named 'sklearn.cluster.Birch'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cluster.KMeans'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 182, in <module>
    from sklearn.cluster.KMeans import train_test_split
ModuleNotFoundError: No module named 'sklearn.cluster.KMeans'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.has_fit_parameter'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 182, in <module>
    from sklearn.utils.validation.has_fit_parameter import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.has_fit_parameter'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cross_decomposition.CCA'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 182, in <module>
    from sklearn.cross_decomposition.CCA import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_decomposition.CCA'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.all_estimators'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 182, in <module>
    from sklearn.utils.all_estimators import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.all_estimators'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.model_selection'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits'), ('to_name', 'shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits'), ('to_name', 'random_state')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_delete'), ('from_name', 'n_splits'), ('to_name', '*')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle'), ('to_name', 'n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, n_splits=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle'), ('to_name', 'random_state')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, random_state=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_delete'), ('from_name', 'shuffle'), ('to_name', '*')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'random_state'), ('to_name', 'n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'random_state'), ('to_name', 'shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_delete'), ('from_name', 'random_state'), ('to_name', '*')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&random_state'), ('to_name', 'shuffle&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&random_state'), ('to_name', 'random_state&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&random_state'), ('to_name', 'random_state&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&random_state'), ('to_name', 'n_splits&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, n_splits=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&random_state'), ('to_name', 'random_state&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, random_state=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&random_state'), ('to_name', 'random_state&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, random_state=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&n_splits'), ('to_name', 'n_splits&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, n_splits=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&n_splits'), ('to_name', 'n_splits&random_state')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, n_splits=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&n_splits'), ('to_name', 'random_state&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, random_state=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&n_splits&random_state'), ('to_name', 'n_splits&random_state&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, n_splits=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&n_splits&random_state'), ('to_name', 'random_state&shuffle&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, random_state=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'shuffle'), ('target_value', 'True')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'shuffle'), ('target_value', 'False')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'shuffle&random_state'), ('target_value', 'True&False')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'shuffle&n_splits'), ('target_value', 'True&False')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[REPAIR EXEC TIME]: 80.96150040626526