


Traceback (most recent call last):
  File "titanic-logistic-regression-7655.py", line 182, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation'), ('line_no', 182)])


Traceback (most recent call last):
  File "titanic-logistic-regression-7655.py", line 183, in <module>
    from sklearn.utils.validation import train_test_split
ImportError: cannot import name 'train_test_split'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cross_decomposition'), ('line_no', 182)])


Traceback (most recent call last):
  File "titanic-logistic-regression-7655.py", line 183, in <module>
    from sklearn.cross_decomposition import train_test_split
ImportError: cannot import name 'train_test_split'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.check_memory'), ('line_no', 182)])


Traceback (most recent call last):
  File "titanic-logistic-regression-7655.py", line 183, in <module>
    from sklearn.utils.validation.check_memory import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.check_memory'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.column_or_1d'), ('line_no', 182)])


Traceback (most recent call last):
  File "titanic-logistic-regression-7655.py", line 183, in <module>
    from sklearn.utils.validation.column_or_1d import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.column_or_1d'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.check_is_fitted'), ('line_no', 182)])


Traceback (most recent call last):
  File "titanic-logistic-regression-7655.py", line 183, in <module>
    from sklearn.utils.validation.check_is_fitted import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.check_is_fitted'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.check_symmetric'), ('line_no', 182)])


Traceback (most recent call last):
  File "titanic-logistic-regression-7655.py", line 183, in <module>
    from sklearn.utils.validation.check_symmetric import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.check_symmetric'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cluster.Birch'), ('line_no', 182)])


Traceback (most recent call last):
  File "titanic-logistic-regression-7655.py", line 183, in <module>
    from sklearn.cluster.Birch import train_test_split
ModuleNotFoundError: No module named 'sklearn.cluster.Birch'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cluster.KMeans'), ('line_no', 182)])


Traceback (most recent call last):
  File "titanic-logistic-regression-7655.py", line 183, in <module>
    from sklearn.cluster.KMeans import train_test_split
ModuleNotFoundError: No module named 'sklearn.cluster.KMeans'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.has_fit_parameter'), ('line_no', 182)])


Traceback (most recent call last):
  File "titanic-logistic-regression-7655.py", line 183, in <module>
    from sklearn.utils.validation.has_fit_parameter import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.has_fit_parameter'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cross_decomposition.CCA'), ('line_no', 182)])


Traceback (most recent call last):
  File "titanic-logistic-regression-7655.py", line 183, in <module>
    from sklearn.cross_decomposition.CCA import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_decomposition.CCA'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.all_estimators'), ('line_no', 182)])


Traceback (most recent call last):
  File "titanic-logistic-regression-7655.py", line 183, in <module>
    from sklearn.utils.all_estimators import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.all_estimators'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.model_selection'), ('line_no', 182)])/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)



              precision    recall  f1-score   support

           0       0.68      0.62      0.65        24
           1       0.77      0.81      0.79        37

    accuracy                           0.74        61
   macro avg       0.73      0.72      0.72        61
weighted avg       0.73      0.74      0.74        61

[REPAIR EXEC TIME]: 22.508471727371216